trigger:
- master

pool:
  vmImage: ubuntu-latest
  
parameters:
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - prod

  - name: version
    displayName: Version
    type: string
    default: latest

variables:
  - name: imageVersion
    value: ${{ parameters.version }}

steps:
- script: Start Building image version $(imageVersion)!
  displayName: 'Build image for environment: ${{ parameters.environment }}'
  
- template: devops/az-devops-templates/dockerhub-push.yml
  parameters:
    IMAGE_NAME: devops-training-python-app-azure
    IMAGE_VERSION:  $(imageVersion)